### ISSUE TITLE
Activating extension 'vector-of-bool.gitflow' failed: The "path" argument must be of type string. Received type undefined.

### ISSUE THREAD

**Issue by ghost** [vector-of-bool/vscode-gitflow#36]
I am trying to build a VSIX extension for the first time, following this [link](https://code.visualstudio.com/api/get-started/your-first-extension) but it fails and seems like it is related to this extension or this dependencies.

When I try to compile the extension for the first time I get this error in the Extension Development Host window

    Activating extension 'vector-of-bool.gitflow' failed: The "path" argument must be of type string. Received type undefined.

In the console, I see this:
```
Failed to execute fetch TypeError: Cannot read property '0' of undefined
at getWorkspaceRootPath (c:\Users\Alex.vscode\extensions\fatihacet.gitlab-workflow-2.2.0\src\git_service.js:5:69)
at fetch (c:\Users\Alex.vscode\extensions\fatihacet.gitlab-workflow-2.2.0\src\git_service.js:11:10)
at fetchRemoteUrl (c:\Users\Alex.vscode\extensions\fatihacet.gitlab-workflow-2.2.0\src\git_service.js:106:28)
Failed to execute fetch TypeError: Cannot read property '0' of undefined
at getWorkspaceRootPath (c:\Users\Alex.vscode\extensions\fatihacet.gitlab-workflow-2.2.0\src\git_service.js:5:69)
at fetch (c:\Users\Alex.vscode\extensions\fatihacet.gitlab-workflow-2.2.0\src\git_service.js:11:10)
at fetchRemoteUrl (c:\Users\Alex.vscode\extensions\fatihacet.gitlab-workflow-2.2.0\src\git_service.js:106:28)
Failed to execute fetch TypeError: Cannot read property '0' of undefined
at getWorkspaceRootPath (c:\Users\Alex.vscode\extensions\fatihacet.gitlab-workflow-2.2.0\src\git_service.js:5:69)
at fetch (c:\Users\Alex.vscode\extensions\fatihacet.gitlab-workflow-2.2.0\src\git_service.js:11:10)
at fetchRemoteUrl (c:\Users\Alex.vscode\extensions\fatihacet.gitlab-workflow-2.2.0\src\git_service.js:106:28)
Failed to execute fetch TypeError: Cannot read property '0' of undefined
at getWorkspaceRootPath (c:\Users\Alex.vscode\extensions\fatihacet.gitlab-workflow-2.2.0\src\git_service.js:5:69)
at fetch (c:\Users\Alex.vscode\extensions\fatihacet.gitlab-workflow-2.2.0\src\git_service.js:11:10)
at fetchRemoteUrl (c:\Users\Alex.vscode\extensions\fatihacet.gitlab-workflow-2.2.0\src\git_service.js:106:28)
Failed to execute fetch TypeError: Cannot read property '0' of undefined
at getWorkspaceRootPath (c:\Users\Alex.vscode\extensions\fatihacet.gitlab-workflow-2.2.0\src\git_service.js:5:69)
at fetch (c:\Users\Alex.vscode\extensions\fatihacet.gitlab-workflow-2.2.0\src\git_service.js:11:10)
at fetchRemoteUrl (c:\Users\Alex.vscode\extensions\fatihacet.gitlab-workflow-2.2.0\src\git_service.js:106:28)
Failed to execute fetch TypeError: Cannot read property '0' of undefined
at getWorkspaceRootPath (c:\Users\Alex.vscode\extensions\fatihacet.gitlab-workflow-2.2.0\src\git_service.js:5:69)
at fetch (c:\Users\Alex.vscode\extensions\fatihacet.gitlab-workflow-2.2.0\src\git_service.js:11:10)
at fetchRemoteUrl (c:\Users\Alex.vscode\extensions\fatihacet.gitlab-workflow-2.2.0\src\git_service.js:106:28)
```
Why would this happen?

**Comment by benjaminfauchald** [comment]
Activating extension 'vector-of-bool.gitflow' failed: The "path" argument must be of type string. Received undefined.

Same problem here...

**Comment by Serhioromano** [comment]
Looks like console log have nothing to do with this extension. What are you doing? You create VS Code Extension and when you start to debug it you see this message?
